### ISSUE TITLE
AWS Key and Queue resources not created

### ISSUE THREAD

**Issue by nzoschke** [convox/praxis#114]
I deployed this manifest to AWS but do not see any KMS or SQS CF resources.

```yaml
resources:
  database:
    type: postgres
services:
  web:
    build: .
    command:
      development: buffalo dev
      test: buffalo test
    environment:
      - ...
    keys:
      racks:
      integrations:
    port: https:3000
    queues:
      racks:
    resources:
      - database
    scale:
      memory: 1024
```

I do have an updated Rack API because my code gets this error trying to use the praxis APIs:

```
ValidationError: Resource KeyRacks does not exist for stack dev2-interface
	status code: 400, request id: b7fdbf9e-2f62-11e7-a62d-0bd9e4946c3a
```
