### ISSUE TITLE
Manifest validation

### ISSUE THREAD

**Issue by nzoschke** [convox/praxis#131]
I mistakenly put the keys/queues directive inside a service. Seems like validation should catch and prevent that.

```resources:
  database:
    type: postgres
services:
  web:
    build: .
    command:
      development: buffalo dev
      test: buffalo test
    environment:
      - ...
    keys:
      racks:
      integrations:
    port: https:3000
    queues:
      racks:
    resources:
      - database
    scale:
      memory: 1024
```

**Comment by nzoschke** [comment]
On #169, the CDN property should validate a hostname but not a full `https://...` URL.

**Comment by nzoschke** [comment]
I got confused by this one not parsing. My intent was to run the 'false' shell command:

```
services:
  web:
    image: httpd
    port: 80
workflows:
  change:
    create:
      - run: false
    update:
      - run: false
```

Putting single quotes around 'false' behaves as expected.
