### ISSUE TITLE
CDN host header error / rollback

### ISSUE THREAD

**Issue by nzoschke** [convox/praxis#169]
```yaml
services:
  proxy:
    build: .
    cdn: ${PROXY_HOST}
    command: proxy
    environment:
      - PROXY_HOST=https://proxy.service.interface.convox
    health: /health
    port: https:3001
    resources:
      - database
  web:
    build: .
    cdn: ${WEB_HOST}
    command:
      development: buffalo dev
      test: buffalo test
    environment:
      - WEB_HOST=https://web.service.interface.convox
      - PROXY_HOST=https://proxy.service.interface.convox
...
```

```
$ cx env --app ui-staging | grep HOST
PROXY_HOST=https://proxy-staging.convox.com
WEB_HOST=https://ui-staging.convox.com
```

```
09:59:29 UTC-0700	UPDATE_ROLLBACK_IN_PROGRESS	AWS::CloudFormation::Stack	staging-ui-staging	The following resource(s) failed to update: [ServiceWebListenerRuleCdnDomain].
09:59:26 UTC-0700	UPDATE_FAILED	AWS::ElasticLoadBalancingV2::ListenerRule	ServiceWebListenerRuleCdnDomain	Condition value for field 'host-header' must be a valid hostname
```
