### ISSUE TITLE
Workflow Design and Implementation

### ISSUE THREAD

**Issue by nzoschke** [convox/praxis#215]
A complete workflow looks like:

```
workflows:
  change:
    create:
      - test: staging
      - create: staging/example-$branch
      - deploy: staging/example-$branch
    update:
      - test: staging
      - deploy: staging/example-$branch
    close:
      - delete: staging/example-$branch
  merge:
    master:
      - test: staging
      - deploy: staging/example-staging
      - copy: production/example-production
```
This begs some design questions.

Is the test rack required?
How are branch names translated to valid app names?
Does a `deploy` step imply a `create` step? What happens if I manually delete the QA app then update the PR and trigger a new update flow?
