### ISSUE TITLE
Volumes Design

### ISSUE THREAD

**Issue by nzoschke** [convox/praxis#229]
I see pieces of volumes support but it's not clear how it will work. Use cases:

* Make the Docker socket available to an app
* Give an app a persistent volume
* Let two or more apps share a persistent volume

The last one is not possible on Rack 1.0 due to making volumes app specific. I propose we fix that with the "from" part of the "from:to" actually referencing the host, so multiple apps can specify the same part.

Perhaps "/volumes/" is a convention here, which is a shared Docker volume locally and the EFS mount point on AWS.

Make the Docker socket available to an app:

```yaml
web:
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
```

Let two apps share a persistent volume:

```yaml
web:
  volumes:
    - /volumes/shared:/data
```

```yaml
web:
  volumes:
    - /volumes/shared:/data
```

Perhaps we still have shorthand for a single app volume?

```yaml
web:
  volumes:
    - /var/www/html
```

This translates to "/volumes/myapp:/var/www/html"
