### ISSUE TITLE
template interpolation for env

### ISSUE THREAD

**Issue by nzoschke** [convox/praxis#318]
I'm playing around with a single HOST variable to control both SSL and the server config. I tried this pattern:

```
services:
  web:
    certificate: ${HOST}
    environment:
      - HOST=web.docs.convox
      - HUGO_BASEURL=${HOST}
```

If I do `HOST=foo cx test` I see `HUGO_BASEURL=foo`. But if I don't specify a value I see `HUGO_BASEURL=` (empty).

I expected the default `web.docs.convox` to show up there.
