### ISSUE TITLE
Code sync is syncing code to the wrong container

### ISSUE THREAD

**Issue by scottmessinger** [convox/praxis#338]
I have two services in my app: backend and frontend. They live in two folders in the root of the directory. My convox file look like:

```yaml
services:
  backend:
    build: ./backend
    # ....
  frontend:
    build: ./frontend
    # ....
```

When I change files in the backend folder, it syncs the changes to the frontend container. For instance:

```
convox   | sync: backend/lib/spikey/plugs/www_redirect.ex to frontend
frontend | file changed backend/lib/spikey/plugs/www_redirect.ex
```
